### PR TITLE
Add a callback to get elapsed recording time in seconds.

### LINKED ISSUE #4: Add elapsed time listener in recording
How can we get elapsed time while recording?

### PR DESCRIPTION
**Pull request by abkoradiya**

### CODE REVIEW

**Comment by squti** [comment]
Please remove .gitignore changes and .idea folder deleted files from your commit and just add kotlin and layout changed files. Also, use **Add** instead of **Added** in your commit message and make a new pull request. Moreover, please make a different commit and pull request for bumping gradle version.

**Comment by abkoradiya** [comment]
So, Do I need to delete the current fork and make a new one?

**Comment by squti** [comment]
No you can revert your commit and make a new one and just add kotlin and layout files. Then use push force to update your fork and make a new pull request.

**Comment by squti** [comment]
Thanks for your changes but now there are 2 commits which first one shows revert and there are 3 commits at all for PR (Include your first commit). I think it's better you reset hard your commits. Copy your changes from your fork and just make one commit consist of appropriate files and make a new PR. If you have any question feel free to ask.

**Comment by abkoradiya** [comment]
Hi can you suggest me how to reset previous history of commit?

**Comment by squti** [comment]
I've merged your commits into one commit . It's ok

**Pull request merged**
